### ISSUE TITLE
Custom startup scripts

### ISSUE THREAD

**Issue by billyfoss** [openinfrastructure/terraform-google-multinic#40]
Would it be possible to support a custom startup script that would run after the default routing startup and configuration scripts?

This could be used with the image_project/image_name parameters to use a custom centos-8 based image and configure additional monitoring, security, etc. in the running VMs.  In our case, we would like to configure monitoring on the VMs.

**Comment by jeffmccune** [comment]
Sure thing, I’ll add this soon. ETA end of the week, early next at the latest.

**Comment by jeffmccune** [comment]
Released in [3.4.0](https://github.com/openinfrastructure/terraform-google-multinic/tree/3.4.0) and [2.1.0](https://github.com/openinfrastructure/terraform-google-multinic/tree/2.1.0)
